site_name: "Farris Family Recipe Book"
theme:
  name: "mkdocs"
# custom_dir: "custom_theme/"  
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: red
      accent: deep-orange
    - scheme: slate
      primary: deep-purple
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"

nav:
  - Home: index.md
  - Categories: categories.md
  - Recipes:
      - Breakfast: recipeBook/breakfast/
      - Dinner and Lunches: recipeBook/dinner-and-lunches/
      - Desserts: recipeBook/Desserts/
      - Sides: recipeBook/sides/
  - Cooking Tips: tips.md
  - About: about.md
