site_name: "Family Recipe Book"
theme:
  name: "mkdocs"
  logo: "img/farrisfamrecipes.png"
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: red
      accent: deep-orange
    - scheme: slate
      primary: deep-purple
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"

nav:
  - Home: index.md
  - Categories: categories.md
  - Recipes:
      - Breakfast: recipeBook/breakfast/index.md
      - Dinner and Lunches: recipeBook/dinner-and-lunches/index.md
      - Desserts: recipeBook/Desserts/index.md
      - Sides: recipeBook/sides/index.md
  - Cooking Tips: tips.md
  - About: about.md
